# Generated by Django 3.1.2 on 2021-01-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('Electronics & Communication', 'Electronics & Communication'), ('Computer Science', 'Computer Science'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical')], max_length=200)),
                ('sem', models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2'), ('semester 3', 'semester 3'), ('semester 4', 'semester 4'), ('semester 5', 'semester 5'), ('semester 6', 'semester 6'), ('semester 7', 'semester 7'), ('semester 8', 'semester 8')], max_length=200)),
                ('reg_no', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('pin_no', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_status', models.BooleanField()),
                ('store_details', models.CharField(blank=True, max_length=300)),
                ('store_balance', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('pickup_time', models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Lunch Break', 'Lunch Break'), ('Last Break', 'Last Break')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('pickup_time', models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Lunch Break', 'Lunch Break'), ('Last Break', 'Last Break')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_break', models.TimeField(null=True)),
                ('lunch_break', models.TimeField(null=True)),
                ('last_break', models.TimeField(null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
            ],
        ),
    ]
