# Generated by Django 3.1.2 on 2022-03-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(blank=True, max_length=200)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("invoice_no", models.SlugField(max_length=10)),
                (
                    "invoice",
                    models.FileField(max_length=254, upload_to="django_field_pdf"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_break", models.TimeField(null=True)),
                ("lunch_break", models.TimeField(null=True)),
                ("last_break", models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(blank=True, max_length=200)),
                ("quantity", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                (
                    "pickup_time",
                    models.CharField(
                        choices=[
                            ("Now", "Now"),
                            ("First Break", "First Break"),
                            ("Lunch Break", "Lunch Break"),
                            ("Last Break", "Last Break"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_name", models.CharField(max_length=200)),
                ("institute_balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200)),
                ("stock", models.IntegerField(default=1)),
                ("price", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(blank=True, max_length=200)),
                ("quantity", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                (
                    "pickup_time",
                    models.CharField(
                        choices=[
                            ("Now", "Now"),
                            ("First Break", "First Break"),
                            ("Lunch Break", "Lunch Break"),
                            ("Last Break", "Last Break"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                ("otp", models.CharField(max_length=4)),
                ("purchase_id", models.IntegerField(default=0)),
                ("revenue", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=200)),
                ("store_status", models.BooleanField()),
                ("store_details", models.CharField(blank=True, max_length=300)),
                ("store_balance", models.IntegerField(default=0)),
                ("invoice_code", models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            (
                                "Electronics & Communication",
                                "Electronics & Communication",
                            ),
                            ("Computer Science", "Computer Science"),
                            ("Civil", "Civil"),
                            ("Mechanical", "Mechanical"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("semester 1", "semester 1"),
                            ("semester 2", "semester 2"),
                            ("semester 3", "semester 3"),
                            ("semester 4", "semester 4"),
                            ("semester 5", "semester 5"),
                            ("semester 6", "semester 6"),
                            ("semester 7", "semester 7"),
                            ("semester 8", "semester 8"),
                        ],
                        max_length=200,
                    ),
                ),
                ("reg_no", models.CharField(max_length=200)),
                ("balance", models.IntegerField(default=0)),
                ("pin_no", models.CharField(max_length=200)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tray.institute"
                    ),
                ),
            ],
        ),
    ]
