# Generated by Django 3.1.2 on 2020-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(default=0),
        ),
    ]
