# Generated by Django 3.1.2 on 2022-03-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.institute'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store'),
        ),
        migrations.AddField(
            model_name='institute',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
        ),
        migrations.AddField(
            model_name='break',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.institute'),
        ),
        migrations.AddField(
            model_name='bill',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store'),
        ),
    ]
