# Generated by Django 3.1.2 on 2021-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(unique=True),
        ),
    ]
