# Generated by Django 3.1.2 on 2021-01-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0002_auto_20210125_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin_no',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
