# Generated by Django 3.1.2 on 2020-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0002_auto_20201015_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
