# Generated by Django 3.1.2 on 2021-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0003_auto_20210125_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.CharField(default='abcd', max_length=4),
            preserve_default=False,
        ),
    ]
