# Generated by Django 3.1.2 on 2020-10-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0003_items_item_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_two',
            new_name='item2',
        ),
    ]
