# Generated by Django 3.1.2 on 2020-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0004_auto_20201017_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
    ]
