# Generated by Django 3.1.2 on 2022-03-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tray", "0005_auto_20220319_1242"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BulkRechargeMails",
            new_name="BulkRechargeMail",
        ),
    ]
