# Generated by Django 3.1.2 on 2021-11-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0006_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='cost',
            new_name='prize',
        ),
    ]
