# Generated by Django 3.1.2 on 2022-03-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0006_auto_20220319_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
