# Generated by Django 3.1.2 on 2020-10-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0007_auto_20201017_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity1',
            field=models.IntegerField(default=1),
        ),
    ]
