# Generated by Django 3.1.2 on 2021-11-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0007_auto_20211119_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='prize',
            new_name='price',
        ),
    ]
