# Generated by Django 3.1.2 on 2022-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tray", "0007_auto_20220319_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="pin_no",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="reg_no",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
