# Generated by Django 3.1.2 on 2020-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0008_auto_20201017_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
