# Generated by Django 4.0.6 on 2022-10-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0008_auto_20220319_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteMerchantCredentails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm_merchant_id', models.CharField(max_length=200)),
                ('paytm_secret_key', models.CharField(max_length=200)),
                ('paytm_website', models.CharField(max_length=200)),
                ('paytm_channel_id', models.CharField(max_length=200)),
                ('paytm_industry_type_id', models.CharField(max_length=200)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
            ],
        ),
    ]
