# Generated by Django 4.0.6 on 2022-10-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0009_institutemerchantcredentails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstituteMerchantCredentails',
            new_name='InstituteMerchantCredentail',
        ),
    ]
