# Generated by Django 3.1.2 on 2021-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0009_bill_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
