# Generated by Django 3.1.2 on 2020-10-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0010_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
