# Generated by Django 4.0.6 on 2022-10-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0011_alter_institute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutemerchantcredentail',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_creds', to='tray.institute'),
        ),
    ]
