# Generated by Django 3.1.2 on 2021-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0011_auto_20211121_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='invoice_code',
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
