# Generated by Django 4.0.6 on 2022-10-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0012_alter_institutemerchantcredentail_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='tray.institute'),
        ),
    ]
