# Generated by Django 3.1.2 on 2020-10-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0012_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_balance',
            field=models.IntegerField(default=0),
        ),
    ]
