# Generated by Django 3.1.2 on 2021-11-22 07:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0014_auto_20211121_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice',
            field=models.FileField(max_length=254, upload_to=django.core.files.storage.FileSystemStorage(location='/django_invoices')),
        ),
    ]
