# Generated by Django 4.0.6 on 2022-10-19 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0014_alter_student_college_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='identification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
