# Generated by Django 3.1.2 on 2020-10-27 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0014_auto_20201027_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tray.store'),
            preserve_default=False,
        ),
    ]
