# Generated by Django 3.1.2 on 2020-10-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0015_item_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
