# Generated by Django 4.0.6 on 2022-10-19 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0015_institute_identification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
