# Generated by Django 3.1.2 on 2020-10-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0016_remove_item_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
