# Generated by Django 4.0.6 on 2022-10-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0017_alter_institute_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutemerchantcredentail',
            old_name='paytm_industry_type_id',
            new_name='paytm_industry_type',
        ),
    ]
