# Generated by Django 3.1.2 on 2020-10-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0017_auto_20201027_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item1',
            new_name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
