# Generated by Django 3.1.2 on 2021-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0018_auto_20211122_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
