# Generated by Django 3.1.2 on 2020-11-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0019_item_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prize',
            field=models.IntegerField(default=0),
        ),
    ]
