# Generated by Django 4.0.6 on 2022-10-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0020_revenue_ordergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='identification_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='identification_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
