# Generated by Django 3.1.2 on 2020-11-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0021_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prize1',
            new_name='cost1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prize2',
            new_name='cost2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prize3',
            new_name='cost3',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prize4',
            new_name='cost4',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prize5',
            new_name='cost5',
        ),
    ]
