# Generated by Django 4.0.6 on 2022-10-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0021_alter_institute_identification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='revenue',
        ),
    ]
