# Generated by Django 3.1.2 on 2020-11-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0022_auto_20201101_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity5',
        ),
        migrations.AddField(
            model_name='order',
            name='Time',
            field=models.CharField(choices=[('A', 'Now'), ('B', 'First Break'), ('C', 'Second Break'), ('D', 'LAst Break')], default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='item1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity1',
            field=models.IntegerField(default=0),
        ),
    ]
