# Generated by Django 4.0.6 on 2022-10-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0022_remove_order_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tray.ordergroup'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='order_group_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
