# Generated by Django 4.0.6 on 2022-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0023_order_order_group_ordergroup_order_group_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
