# Generated by Django 3.1.2 on 2020-11-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0023_auto_20201101_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
            preserve_default=False,
        ),
    ]
