# Generated by Django 3.1.2 on 2020-11-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0024_order_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Student',
        ),
    ]
