# Generated by Django 3.1.2 on 2020-11-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0025_remove_order_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
            preserve_default=False,
        ),
    ]
