# Generated by Django 4.0.6 on 2022-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0025_ordergroup_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='total',
        ),
    ]
