# Generated by Django 4.0.6 on 2022-10-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0029_subscriptionplans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutemerchantcredentail',
            old_name='paytm_channel_id',
            new_name='razorpay_key_id',
        ),
        migrations.RenameField(
            model_name='institutemerchantcredentail',
            old_name='paytm_industry_type',
            new_name='razorpay_key_secret',
        ),
        migrations.RenameField(
            model_name='institutemerchantcredentail',
            old_name='paytm_merchant_id',
            new_name='razorpay_merchant_id',
        ),
        migrations.RemoveField(
            model_name='institutemerchantcredentail',
            name='paytm_secret_key',
        ),
        migrations.RemoveField(
            model_name='institutemerchantcredentail',
            name='paytm_website',
        ),
    ]
