# Generated by Django 3.1.2 on 2020-11-02 19:31

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0029_auto_20201102_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_on',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
