# Generated by Django 4.0.6 on 2022-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0030_rename_paytm_channel_id_institutemerchantcredentail_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutemerchantcredentail',
            name='razorpay_key_id',
        ),
        migrations.RemoveField(
            model_name='institutemerchantcredentail',
            name='razorpay_key_secret',
        ),
        migrations.RemoveField(
            model_name='institutemerchantcredentail',
            name='razorpay_merchant_id',
        ),
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='paytm_channel_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='paytm_industry_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='paytm_merchant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='paytm_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='paytm_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
