# Generated by Django 3.1.2 on 2020-11-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0030_auto_20201102_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
