# Generated by Django 4.0.6 on 2022-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0031_remove_institutemerchantcredentail_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrechargemail',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
