# Generated by Django 3.1.2 on 2020-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0032_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
