# Generated by Django 4.0.6 on 2022-11-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0032_bulkrechargemail_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrechargemail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
        ),
    ]
