# Generated by Django 4.0.6 on 2022-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0033_bulkrechargemail_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemerchantcredentail',
            name='fee_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
