# Generated by Django 3.1.2 on 2020-11-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0034_auto_20201102_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prize',
            new_name='price',
        ),
    ]
