# Generated by Django 3.1.2 on 2020-11-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0035_auto_20201108_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity1',
            new_name='stock',
        ),
    ]
