# Generated by Django 4.0.6 on 2022-11-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0035_remove_institutemerchantcredentail_fee_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student')),
            ],
        ),
    ]
