# Generated by Django 3.1.2 on 2020-11-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0036_auto_20201108_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Second Break', 'Second Break'), ('Last Break', 'LAst Break')], max_length=200),
        ),
    ]
