# Generated by Django 4.0.6 on 2022-11-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0037_bill_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tray.student'),
        ),
    ]
