# Generated by Django 3.1.2 on 2020-11-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0038_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Electronics & Communication', 'Electronics & Communication'), ('Computer Science', 'Computer Science'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical')], default='Civil', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pin_no',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2'), ('semester 3', 'semester 3'), ('semester 4', 'semester 4'), ('semester 5', 'semester 5'), ('semester 6', 'semester 6'), ('semester 7', 'semester 7'), ('semester 8', 'semester 8')], default='semester 8', max_length=200),
            preserve_default=False,
        ),
    ]
