# Generated by Django 4.0.6 on 2022-11-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0038_alter_ordergroup_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('today', 'today'), ('upcoming', 'upcoming')], max_length=200)),
                ('event_image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tray.institute')),
            ],
        ),
    ]
