# Generated by Django 4.0.6 on 2022-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0039_instituteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteevent',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteevent',
            name='title',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
