# Generated by Django 3.1.2 on 2020-11-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0041_break'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Break',
        ),
    ]
