# Generated by Django 3.1.2 on 2020-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0042_delete_break'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.TimeField()),
                ('first_break', models.TimeField()),
                ('lunch_break', models.TimeField()),
                ('last_break', models.TimeField()),
            ],
        ),
    ]
