# Generated by Django 3.1.2 on 2020-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0043_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='now',
        ),
        migrations.AlterField(
            model_name='break',
            name='first_break',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='last_break',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='lunch_break',
            field=models.TimeField(null=True),
        ),
    ]
