# Generated by Django 3.1.2 on 2020-11-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0044_auto_20201124_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Lunch Break', 'Lunch Break'), ('Last Break', 'LAst Break')], max_length=200),
        ),
    ]
