# Generated by Django 3.1.2 on 2020-11-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0045_auto_20201126_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Lunch Break', 'Lunch Break'), ('Last Break', 'Last Break')], max_length=200),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('pickup_time', models.CharField(choices=[('Now', 'Now'), ('First Break', 'First Break'), ('Lunch Break', 'Lunch Break'), ('Last Break', 'Last Break')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.student')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tray.store')),
            ],
        ),
    ]
