# Generated by Django 3.1.2 on 2020-11-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0046_auto_20201130_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cost1',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item1',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Time',
            new_name='pickup_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stock',
            new_name='quantity',
        ),
    ]
