# Generated by Django 3.1.2 on 2020-11-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0047_auto_20201130_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='cost',
        ),
    ]
