# Generated by Django 3.1.2 on 2020-11-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0048_auto_20201130_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Student',
            new_name='student',
        ),
    ]
