# Generated by Django 3.1.2 on 2020-11-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0049_auto_20201130_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Student',
            new_name='student',
        ),
    ]
