from itertools import islice

from reportlab.lib import colors
from reportlab.lib.pagesizes import inch, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Frame,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

styles = getSampleStyleSheet()
styleN = styles["Normal"]
styleH = styles["Heading1"]
style = styles["BodyText"]
# filename & variables
# fileName = 'invoice.pdf'
documentTitle = "invoice"
title = "ALLTRAY"
subTitle = "Kattiparambil, Manjummel, 683501"
line = "_________________________________"
credits = "                              generated by alltray"
initLines = [
    "Date:",
    "Invoice no. ",
    line,
    "Item                      Qty    Price     Amount",
    line,
    line,
]

finalLines = [
    "Total:",
    line,
    "GRAND TOTAL:",
    line,
    "Recieved amount:",
    "Balance amount:",
    "",
    "",
    "                Authorized signatory",
    "",
    "",
    "",
    "",
]


# insert orders into array : textLine
def add_orders(load):
    i = 4
    initLines.insert(5, "cake")
    initLines.insert(6, "chocolate")
    # for order in load:
    # 	i=i+1


def create_invoice(store_name, new_invoice_no, load, total):
    # creating file name from invoice no
    filename = str(new_invoice_no)
    # canvas size and filename
    pdf = canvas.Canvas("media/pdf/canvas_pdf", pagesize=(200, 350))
    # drawing title text
    pdf.setFontSize(15)
    pdf.drawCentredString(100, 325, store_name)
    pdf.setFontSize(10)
    pdf.drawCentredString(100, 310, subTitle)
    pdf.drawCentredString(100, 300, "___________________________")
    # set text starting coordinates
    text = pdf.beginText(10, 275)
    text.setFont("Helvetica", 10)

    # write initial text
    for line in initLines:
        text.textLine(line)

    doc = SimpleDocTemplate("media/pdf/" + filename, pagesize=(250, 350))
    # final array to print table
    elements = []
    order_titles = ["Item", "Qty", "Price", "Cost"]
    elements.append(Paragraph(store_name, styleH))
    elements.append(Paragraph("Invoice no: " + new_invoice_no, style))
    elements.append(Paragraph("Manjummel Edappaly"))
    # doc.build(elements)

    # length of load list
    i = len(load)
    print("i is: " + str(i))
    # array to store order values
    order_values = []
    for c in range(i):
        for key in load[c].keys():
            order_values.append(load[c][key])

    print(order_values)
    length = []
    # initing length array for sublists
    for l in range(i):
        length.append(4)
    # forming list of lists
    input = iter(order_values)
    orders = [list(islice(input, elem)) for elem in length]
    orders.insert(0, order_titles)
    print(orders)

    # table function
    t = Table(orders)
    t.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.25, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.black),
            ]
        )
    )
    elements.append(t)
    # printing total
    elements.append(Paragraph("Total: " + total, styleH))
    elements.append(Paragraph("generated by Alltray ", style))
    # printing to pdf
    doc.build(elements)
    # f = Frame(inch, inch, 6*inch, 9*inch, showBoundary=1)
    # f.addFromList(elements,pdf)

    # write final text
    for line in finalLines:
        text.textLine(line)

    text.setFont("Helvetica", 7)
    text.textLine(credits)

    pdf.drawText(text)
    # save the pdf

    print("invoice created!")
